language: cpp
sudo: required
dist: trusty
os: linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-8
script:
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 50
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 50
    - g++ --version
    - gcc --version
      #- wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.sh
      #- sudo sh cmake-3.11.4-Linux-x86_64.sh --skip-license --prefix=/usr/local
      #- cmake --version
